"""
Prometheus metrics for monitoring DevDocs AI.

This module provides Prometheus metrics for tracking:
- Query performance (latency, throughput)
- Cache effectiveness (hit rates)
- LLM usage (tokens generated)
- Retrieval quality (chunks retrieved)
- Ingestion progress (files, chunks)
"""

from prometheus_client import Counter, Histogram, Gauge, generate_latest, CONTENT_TYPE_LATEST

# ============================================================================
# Request Metrics
# ============================================================================

query_counter = Counter(
    'devdocs_queries_total',
    'Total number of queries processed',
    ['endpoint', 'status']  # endpoint: query/stream, status: success/error
)

query_latency = Histogram(
    'devdocs_query_latency_seconds',
    'Query processing time in seconds',
    ['endpoint'],  # query or stream
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0)
)

# ============================================================================
# Cache Metrics
# ============================================================================

cache_hit_counter = Counter(
    'devdocs_cache_hits_total',
    'Total cache hits',
    ['cache_type']  # embedding or response
)

cache_miss_counter = Counter(
    'devdocs_cache_misses_total',
    'Total cache misses',
    ['cache_type']  # embedding or response
)

cache_hit_rate = Gauge(
    'devdocs_cache_hit_rate',
    'Current cache hit rate (0.0 to 1.0)',
    ['cache_type']  # embedding or response
)

# ============================================================================
# LLM Metrics
# ============================================================================

llm_requests = Counter(
    'devdocs_llm_requests_total',
    'Total LLM generation requests',
    ['model', 'streaming']  # model name, streaming: true/false
)

llm_latency = Histogram(
    'devdocs_llm_latency_seconds',
    'LLM generation time in seconds',
    ['model', 'streaming'],
    buckets=(1.0, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0)
)

tokens_generated = Counter(
    'devdocs_llm_tokens_generated_total',
    'Total tokens generated by LLM',
    ['model']
)

# ============================================================================
# Retrieval Metrics
# ============================================================================

retrieval_chunks = Histogram(
    'devdocs_retrieval_chunks_count',
    'Number of chunks retrieved per query',
    buckets=(1, 3, 5, 10, 20, 50)
)

retrieval_latency = Histogram(
    'devdocs_retrieval_latency_seconds',
    'Vector search time in seconds',
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.0)
)

# ============================================================================
# Ingestion Metrics
# ============================================================================

files_ingested = Counter(
    'devdocs_files_ingested_total',
    'Total files ingested',
    ['language', 'status']  # language: python/js/etc, status: success/error
)

chunks_created = Counter(
    'devdocs_chunks_created_total',
    'Total chunks created',
    ['language', 'chunking_strategy']  # language, strategy: ast/character
)

ingestion_latency = Histogram(
    'devdocs_ingestion_latency_seconds',
    'File ingestion time in seconds',
    ['language'],
    buckets=(0.1, 0.5, 1.0, 5.0, 10.0, 30.0)
)

# ============================================================================
# Embedding Metrics
# ============================================================================

embeddings_generated = Counter(
    'devdocs_embeddings_generated_total',
    'Total embeddings generated',
    ['source']  # source: ingestion/query
)

embedding_latency = Histogram(
    'devdocs_embedding_latency_seconds',
    'Embedding generation time in seconds',
    ['batch_size'],  # batch_size: 1/32/etc
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 5.0)
)

# ============================================================================
# System Metrics
# ============================================================================

active_connections = Gauge(
    'devdocs_active_connections',
    'Number of active WebSocket connections'
)

chromadb_documents = Gauge(
    'devdocs_chromadb_documents_total',
    'Total documents in ChromaDB'
)

chromadb_collections = Gauge(
    'devdocs_chromadb_collections_total',
    'Total collections in ChromaDB'
)

# ============================================================================
# Helper Functions
# ============================================================================

def export_metrics() -> bytes:
    """
    Export all metrics in Prometheus text format.

    Returns:
        Metrics as bytes in Prometheus exposition format

    Example:
        >>> metrics = export_metrics()
        >>> print(metrics.decode('utf-8'))
        # HELP devdocs_queries_total Total number of queries processed
        # TYPE devdocs_queries_total counter
        devdocs_queries_total{endpoint="query",status="success"} 42.0
        ...
    """
    return generate_latest()


def get_content_type() -> str:
    """
    Get the Prometheus content type for HTTP responses.

    Returns:
        Content type string for Prometheus metrics
    """
    return CONTENT_TYPE_LATEST


def update_cache_metrics(cache_stats: dict):
    """
    Update cache hit rate gauges from cache statistics.

    Args:
        cache_stats: Dictionary with hit_rate, embedding_hits, etc.

    Example:
        >>> stats = {
        ...     "hit_rate": 0.75,
        ...     "embedding_hits": 100,
        ...     "embedding_misses": 20,
        ...     "response_hits": 50,
        ...     "response_misses": 10,
        ... }
        >>> update_cache_metrics(stats)
    """
    # Calculate individual hit rates
    embedding_total = cache_stats.get("embedding_hits", 0) + cache_stats.get("embedding_misses", 0)
    response_total = cache_stats.get("response_hits", 0) + cache_stats.get("response_misses", 0)

    if embedding_total > 0:
        embedding_rate = cache_stats.get("embedding_hits", 0) / embedding_total
        cache_hit_rate.labels(cache_type="embedding").set(embedding_rate)

    if response_total > 0:
        response_rate = cache_stats.get("response_hits", 0) / response_total
        cache_hit_rate.labels(cache_type="response").set(response_rate)


def update_chromadb_metrics(vector_store):
    """
    Update ChromaDB metrics (document count, collection count).

    Args:
        vector_store: VectorStore instance to query

    Example:
        >>> from app.services.retrieval import get_vector_store
        >>> store = get_vector_store()
        >>> update_chromadb_metrics(store)
    """
    try:
        chromadb_documents.set(vector_store.count())
        chromadb_collections.set(vector_store.collection_count())
    except Exception:
        # Silently fail - metrics are optional
        pass
